### ISSUE TITLE
Error when trying to deserialize a rbxm file

### ISSUE THREAD

**Issue by ActualMasterOogway** [tapple/pyrxbm#1]
I get this error: `Traceback (most recent call last):
  File "pythoneFilePath", line 43, in <module>
    FILE.deserialize(file)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrxbm\binary.py", line 1854, in deserialize
    handler.deserialize(chunk_stream, self)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrxbm\binary.py", line 824, in deserialize
    raise NotImplementedError(
NotImplementedError: Unhandled property type: PropertyType.UniqueId in PropertyType.UniqueId Folder.HistoryId!`

**I have lz4 and numpy installed**

**Comment by tapple** [comment]
this library is very incomplete. Only yesterday did I get it complete enough to read and write KeyframeSequence assets. It's nowhere near supporting full place files. Contributions welcome. It only currently supports the 6 propertytypes needed to read KeyframeSequences: String, Enum, Float, Int64, Bool, CFrame. There's still about 40 to go, including UniqueID

**Comment by tapple** [comment]
I implemented UniqueId today: https://github.com/tapple/pyrxbm/commit/1c91143663ae42859f7ee5627bbb4b79306f323d
